apiVersion: backend/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            # Example below, change accordingly
#            - name: NODE_ENV
#              valueFrom:
#                secretKeyRef:
#                  name: web-secret
#                  key: NODE_ENV
#            - name:
#              value:
            # Example above, change accordingly
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: askgov-backend-secret
                  key: SECRET_KEY