version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./backups:/backups

  pg_backup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backups:/backups
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    entrypoint: [ "/bin/bash", "-c", "/backups/backup.sh" ]

volumes:
  postgres_data:
