# Generated by Django 5.1 on 2024-09-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0004_rename_date_question_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='state',
        ),
        migrations.AddField(
            model_name='answer',
            name='draft',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
