# Generated by Django 5.1 on 2024-10-09 07:13

import django.db.models.deletion
from django.db import migrations, models


def update_attachment_question(apps, schema_editor):
    Attachment = apps.get_model('ask_gov', 'Attachment')
    for attachment in Attachment.objects.all():
        attachment.question = attachment.answer.question.id
        attachment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0010_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ask_gov.question'),
        ),
        migrations.RunPython(update_attachment_question)
    ]
