# Generated by Django 5.1 on 2024-10-09 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0011_attachment_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='answer',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ask_gov.question'),
        ),
    ]
