# Generated by Django 5.1 on 2024-10-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0012_remove_attachment_answer_alter_attachment_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='filekey',
            new_name='file_key',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='filesize',
            new_name='file_size',
        ),
    ]
