# Generated by Django 5.1 on 2024-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0013_rename_filekey_attachment_file_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='name_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name_ms',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_ms',
            field=models.CharField(null=True),
        ),
    ]
