# Generated by Django 5.1 on 2024-12-04 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0014_agency_name_en_topic_title_en_alter_agency_name_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='admin_opened_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='staff_opened_at',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('question_created', 'Question created'), ('question_opened', 'Question opened'), ('question_answered', 'Question answered'), ('question_assigned', 'Question assigned'), ('answer_updated', 'Answer updated')])),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ask_gov.agency')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_gov.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
