apiVersion: apps/v1
kind: Deployment
metadata:
  name: askgov-website
spec:
  template:
    spec:
      containers:
        - name: askgov-website
          env:
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: API_URL
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: APP_ENV
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: APP_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: AWS_REGION
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: BASE_URL
            - name: ELASTICSEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: ELASTICSEARCH_API_KEY
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: ELASTICSEARCH_URL
            - name: FILE_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: FILE_AWS_ACCESS_KEY_ID
            - name: FILE_AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: FILE_AWS_BUCKET_NAME
            - name: FILE_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: FILE_AWS_SECRET_ACCESS_KEY
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextauth-secret
                  key: NEXTAUTH_SECRET
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: NEXTAUTH_URL
            - name: SES_EMAIL_SOURCE
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: SES_EMAIL_SOURCE
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: askgovfe-secret
                  key: OPENAI_API_KEY
