from django.urls import path, include
from .views import (
    CompletedQuestionListView, QuestionDetailView, AgencyListView, SubmitQuestionView, 
    QuestionsByAgencyView, UserAgencyQuestionsView, SubmitAnswerView, 
    UserAgencyTopicsView, AddTopicView, TopicListView, LikeQuestionView, DislikeQuestionView,
    AssignAgencyToQuestionView, AddAgencyView, AllQuestionListView, TrendingAgenciesView,
    UpdateAgencyView, ChangeAdminIsOpenView, ChangeStaffIsOpenView, SaveDraftQuestionView,
    MarkQuestionAsSpamView, UnSpamQuestionView, UserView, SessionView, AccountView, 
    VerificationTokenView, AddUserView, EditUserView, DeleteUserView, GetAllUsersView, 
    CheckUserEmailExistsView 
)

urlpatterns = [
    path('questions/', CompletedQuestionListView.as_view(), name='question-list-create'),
    path('questions/all/', AllQuestionListView.as_view(), name='all-user-questions'),
    path('questions/<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('agencies/', AgencyListView.as_view(), name='agency-list'),
    path('agencies/<int:pk>/', UpdateAgencyView.as_view(), name='update-agency'),
    path('submit-question/', SubmitQuestionView.as_view(), name='submit-question'),
    path('questions/by-agency/<int:agency_id>/', QuestionsByAgencyView.as_view(), name='questions-by-agency'),
    path('questions/user-agency/', UserAgencyQuestionsView.as_view(), name='user-agency-questions'),
    path('questions/<int:question_id>/submit-answer/', SubmitAnswerView.as_view(), name='submit-answer'),
    path('topics/user-agency/<int:agency_id>/', UserAgencyTopicsView.as_view(), name='user-agency-topics'),
    path('topics/add/<int:agency_id>/', AddTopicView.as_view(), name='add-topic'),
    path('topics/', TopicListView.as_view(), name='topics-list'),
    path('questions/<int:question_id>/like/', LikeQuestionView.as_view(), name='like-question'),
    path('questions/<int:question_id>/dislike/', DislikeQuestionView.as_view(), name='dislike-question'),
    path('questions/<int:question_id>/agency/', AssignAgencyToQuestionView.as_view(), name='assign-agency-to-question'), 
    path('agencies/add/', AddAgencyView.as_view(), name='add-agency'),
    path('agencies/trending/', TrendingAgenciesView.as_view(), name='trending-agencies'),
    path('questions/<int:question_id>/admin_isopen/', ChangeAdminIsOpenView.as_view(), name='change-admin-isopen'),
    path('questions/<int:question_id>/staff_isopen/', ChangeStaffIsOpenView.as_view(), name='change-staff-isopen'),
    path('questions/<int:question_id>/save-draft/', SaveDraftQuestionView.as_view(), name='save-draft'),
    path('questions/<int:question_id>/mark-spam/', MarkQuestionAsSpamView.as_view(), name='mark-question-spam'),
    path('questions/<int:question_id>/un-spam/', UnSpamQuestionView.as_view(), name='mark-question-spam'),
    path('api/auth/user', UserView.as_view(), name='user'),
    path('api/auth/session', SessionView.as_view(), name='session'),
    path('api/auth/account', AccountView.as_view(), name='account'),
    path('api/auth/verification', VerificationTokenView.as_view(), name='verification'),
    path('api/admin/user', AddUserView.as_view(), name='add_user'),
    path('api/admin/user/<int:id>', EditUserView.as_view(), name='edit_user'),
    path('api/admin/user/<int:id>', DeleteUserView.as_view(), name='delete_user'),
    path('api/admin/users', GetAllUsersView.as_view(), name='get_all_users'),
    path('api/admin/check-email', CheckUserEmailExistsView.as_view(), name='check_email_exists'),
]
