apiVersion: apps/v1
kind: Deployment
metadata:
  name: askgov-website
  labels:
    app: askgov-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: askgov-website
  template:
    metadata:
      labels:
        app: askgov-website
    spec:
      containers:
        - name: askgov-website
          image: IMAGE_NAME_PLACEHOLDER
          ports:
            - containerPort: 3000
