---
apiVersion: v1
kind: Service
metadata:
  name: askgov-website
spec:
  type: ClusterIP
  selector:
    app: askgov-website
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: askgov-website
spec:
  serviceRef:
    name: askgov-website
    port: 3000
  targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-1:767397910274:targetgroup/askgov/9dcc41bf255c7223
