apiVersion: batch/v1
kind: CronJob
metadata:
  name: askgov-sync-likes-dislikes
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: askgov-sync-likes-dislikes
              image: IMAGE_NAME_PLACEHOLDER
              command: ["python", "manage.py", "sync_likes_dislikes"]
          restartPolicy: OnFailure
