apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: IMAGE_NAME_PLACEHOLDER
    newName: 0129471803.dkr.ecr.ap-southeast-1.amazonaws.com/askgov-website