# Generated by Django 5.0 on 2024-06-26 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_gov.agency'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, to='ask_gov.topic'),
        ),
    ]
