# Generated by Django 5.0 on 2024-08-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider_account_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='refresh_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name_ms',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_token',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_ms',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('super_admin', 'Super Admin')], default='staff'),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='identifier',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(),
        ),
    ]
