# Generated by Django 5.0 on 2024-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
