# Generated by Django 5.0.6 on 2024-06-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='acronym_en',
            new_name='acronym',
        ),
    ]
