# Generated by Django 5.1 on 2024-08-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0002_alter_account_access_token_alter_account_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_preview',
            field=models.CharField(blank=True, null=True),
        ),
    ]
