# Generated by Django 5.0 on 2024-06-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0002_alter_question_agency_alter_question_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
