# Generated by Django 5.0 on 2024-07-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0003_question_dislikes_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='name_ms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
