# Generated by Django 5.1 on 2024-09-20 02:28

import django.db.models.deletion
from django.db import migrations, models


def migrate_answers(apps, editor_schema):
    Question = apps.get_model('ask_gov', 'Question')
    Answer = apps.get_model('ask_gov', 'Answer')
    for question in Question.objects.all():
        raw = question.temp_answer
        text = question.temp_answer_preview
        likes = question.likes
        dislikes = question.dislikes
        answer = Answer.objects.create(
            raw=raw,
            text=text,
            likes=likes,
            dislikes=dislikes,
            question=question
        )
        answer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0003_question_answer_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ask_gov.agency'),
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='temp_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_preview',
            new_name='temp_answer_preview',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField()),
                ('text', models.CharField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ask_gov.question')),
            ],
        ),
        migrations.RunPython(migrate_answers),
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='temp_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='temp_answer_preview',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answered_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
