# Generated by Django 5.1 on 2024-09-19 03:25

from django.db import migrations
from django.db.models import Q


"""
This function populates the 'name_ms' field for Agency and 'title_ms' field for
Topic with the values from 'name' and 'title' fields respectively, for records
where 'name_ms' or 'title_ms' is empty or null.
"""
def populate_ms_fields(apps, schema_editor):
    Agency = apps.get_model('ask_gov', 'Agency')
    for agency in Agency.objects.filter(Q(name_ms='') | Q(name_ms__isnull=True)):
        agency.name_ms = agency.name
        agency.save()

    Topic = apps.get_model('ask_gov', 'Topic')
    for topic in Topic.objects.filter(Q(title_ms='') | Q(title_ms__isnull=True)):
        topic.title_ms = topic.title
        agency.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0003_question_answer_preview'),
    ]

    operations = [
        migrations.RunPython(populate_ms_fields),
    ]
