# Generated by Django 5.1 on 2024-09-23 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0003_question_answer_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='attachments',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filekey', models.CharField(max_length=255, verbose_name='S3 File Key')),
                ('filesize', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ask_gov.question')),
            ],
        ),
    ]
