# Generated by Django 5.1 on 2024-09-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0004_remove_question_attachments_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='question',
            new_name='question_id',
        ),
    ]
