# Generated by Django 5.1 on 2024-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0004_populate_ms_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='acronym',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name_ms',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_ms',
            field=models.CharField(),
        ),
    ]
