# Generated by Django 5.0 on 2024-07-22 02:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0004_agency_name_ms_topic_title_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='admin_isopen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='answered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='question',
            name='staff_isopen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('completed', 'Completed'), ('spam', 'Spam'), ('draft', 'Draft')], default='backlog', max_length=10),
        ),
    ]
