# Generated by Django 5.1 on 2024-09-23 06:30

from django.db import migrations, models
from django.utils import timezone

def convert_isopen_fields_to_date(apps, schema_editor):
    Question = apps.get_model("ask_gov", "Question")

    for question in Question.objects.filter(admin_isopen=True):
        question.admin_opened_at = timezone.now()
        question.save()

    for question in Question.objects.filter(staff_isopen=True):
        question.staff_opened_at = timezone.now()
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0005_remove_question_state_answer_draft_question_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admin_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='staff_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(convert_isopen_fields_to_date),
        migrations.RemoveField(
            model_name='question',
            name='admin_isopen',
        ),
        migrations.RemoveField(
            model_name='question',
            name='staff_isopen',
        ),
    ]
