# Generated by Django 5.1 on 2024-09-24 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0007_remove_question_attachments_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='question_id',
        ),
        migrations.AddField(
            model_name='attachment',
            name='answer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ask_gov.answer'),
            preserve_default=False,
        ),
    ]
