# Generated by Django 5.1 on 2024-09-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gov', '0008_remove_attachment_question_id_attachment_answer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='answer_id',
            new_name='answer',
        ),
    ]
